# 1ª Lei de Kirchoff

**A somatória das correntes em um nó é zero.**

![](https://github.com/arqMedes/imgCirc/blob/35f02a7e786ac42a88064e864db9f275f5de8273/grafo_circ_elet.png?raw=true)


$$
\begin{cases}
nó \hspace{2mm}  A: -i_1 + i_2  = 0 \\
nó \hspace{2mm} B: +i_1 -i_3 + i_5  = 0 \\
nó \hspace{2mm} D: -i_2 + i_3 + i_4  = 0
\end{cases}
$$

        
Reescrevendo:      



$$
\begin{bmatrix} -1 & 1  & 0 & 0 & 0\\ 
 1 & 0  & -1 & 0 & 1\\
 0 & -1  & 1 & 1 & 0\end{bmatrix}
\times\begin{bmatrix} i_1 \\ i_2 \\ i_3 \\i_4 \\ i_5 \end{bmatrix} = 
\begin{bmatrix} 0 \\ 0 \\0 \\0 \\ 0 \end{bmatrix}
$$


<center><font color="#008B8B" face="verdana" size="5">A.I = 0</center> , onde A: matriz de incidência nó - ramos
           

|Elemento de A|Valor|Descrição|
|---|---|---|
|$a_{ij}$|1|se a corrente do ramo j sai do nó i|
|$a_{ij}$|-1|se a corrente do ramo j entra no nó i
|$a_{ij}$|0|se a corrente do ramo j não incide no nó i

A tensão de cada ramo é dada por:
    
$$
\begin{cases}
ramo \hspace{2mm}  1: v_1 = E_B - E_A \\
ramo \hspace{2mm} 2: v_2 = E_A - E_D \\
ramo \hspace{2mm} 3: v_3 =  E_D - E_B \\
ramo \hspace{2mm} 4: v_4 = E_D \\
ramo \hspace{2mm} 5: v_5 = E_B 
\end{cases}
$$

Matricialmente:
    
$$
\begin{bmatrix} -1 & 1  & 0\\ 
 1 & 0  & -1 \\
 0 & -1  & 1 \\
 0 & 0  & 1 \\
 0 & 1  & 0 \end{bmatrix}
\times\begin{bmatrix} E_A \\ E_B \\ E_D  \end{bmatrix} = 
\begin{bmatrix} v_1 \\v_2 \\v_3 \\ v_4 \\ v_5  \end{bmatrix}
$$



Observe que $V = A^t.E$
    

In [16]:
import numpy as np

#Número de ramos 
r = 5
#Número de nós 
n = 4 - 1  # Um nó é o de referência

A = np.zeros((n , r))

# ramo r1
A[0, 0] = -1
A[1, 0] =  1

# ramo r2
A[0, 1] = 1
A[2, 1] = -1

# ramo r3
A[1, 2] = -1
A[2, 2] = 1

# ramo r4
A[2, 3] = 1

# ramo r5
A[1, 4] = 1

G = np.zeros((r, r))
G[0, 0] = 7./10
G[1, 1] = 1./5
G[2, 2] = 1./10
G[3, 3] = 1./4
G[4, 4] = 1./2

A = np.matrix(A)
G = np.matrix(G)
Gbarra = A*G*A.T

Vs = np.zeros((r, 1))
Is = np.zeros((r, 1))
Is[0,0] = 1
Is[1,0] = -2
Is[3,0] = -3

Is = np.matrix(Is)
Vs = np.matrix(Vs)


Is_no = A*(G*Vs - Is)
E = Gbarra.I*Is_no

In [17]:
Gbarra

matrix([[ 0.9 , -0.7 , -0.2 ],
        [-0.7 ,  1.3 , -0.1 ],
        [-0.2 , -0.1 ,  0.55]])

In [18]:
Is_no

matrix([[ 3.],
        [-1.],
        [ 1.]])

In [19]:
E

matrix([[7.15789474],
        [3.47368421],
        [5.05263158]])

Exemplo:
    
![](https://github.com/arqMedes/imgCirc/blob/master/anNodal.png?raw=true)

![](https://github.com/arqMedes/imgCirc/blob/master/grafo_circ01.png?raw=true)

In [13]:
#Número de ramos 
r = 9
#Número de nós 
n = 4 - 1  # Um nó é o de referência

In [14]:
import numpy as np
A = np.zeros((n , r))

In [15]:
# ramo r1
A[0, 0] = 1
A[2, 0] = -1

# ramo r2
A[0, 1] = -1
A[2, 1] = 1

# ramo r3
A[0, 2] = 1
A[2, 2] = -1

# ramo r4
A[0, 3] = 1
A[1, 3] = -1

# ramo r5
A[0, 4] = -1
A[1, 4] = 1

# ramo r6
A[1, 5] = 1
A[2, 5] = -1

# ramo r7
A[2, 6] = 1

# ramo r8
A[1, 7] = 1

# ramo r9
A[1, 8] = -1

A


array([[ 1., -1.,  1.,  1., -1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  1.,  1.,  0.,  1., -1.],
       [-1.,  1., -1.,  0.,  0., -1.,  1.,  0.,  0.]])

Ramo genérico:
    

![](https://github.com/arqMedes/imgCirc/blob/master/ramoGenerico.png?raw=true)
    
$i_k = I_{sk} + G.(v_k - V_{sk})$

Considerando todos os ramos. Matricialmente, temos:

$I = I_{s} + G.(V - V_{s})$

Multiplica-se por A ambos os membros da equação.

$A.I = A.(I_{s} + G.(V - V_{s}))$

$0 = A.I_{s} + A.G.(A^t.E - V_{s})$, onde $V = A^t.E$

$ (A.G.A^t).E = A(G.V_{s} - I_s)$

$ G_{barra}.E = I_{s(nó)}$, onde $G_{barra} = (A.G.A^t)^{-1} $ e $I_{s(nó)} = A(G.V_{s} - I_s)$

Portanto,

> $E = G_{barra}^{-1}.I_{s(nó)}$

In [ ]:
G = np.zeros((r, r))
G[0, 0] = 1./5
G[1, 1] = 1.e-10
G[2, 2] = 1./2
G[3, 3] = 1./5
G[4, 4] = 1.e-10
G[5, 5] = 1./10
G[6, 6] = 1./2
G[7, 7] = 1./4
G[8, 8] = 1.e-10

Vs = np.zeros((r, 1))
Is = np.zeros((r, 1))
Is[1,0] = 1
Is[4,0] = 2
Is[8,0] = 3

Is = np.matrix(Is)
Vs = np.matrix(Vs)
G = np.matrix(G)
A = np.matrix(A)
Gbarra = A*G*A.T
Is_no = A*(G*Vs - Is)
E = Gbarra.I*Is_no
Gbarra

In [ ]:
Is_no

In [ ]:
E

In [ ]:
$\begin{pmatrix} 1 & 4 & 0 \\ -2 & 4 & 3\end{pmatrix} \times\begin{pmatrix} 1 \\ 0 \\ -3\end{pmatrix} = \begin{pmatrix} 1 \\ -11\end{pmatrix}$

In [ ]:
$$
\left[ \begin{array}{rrrrr}
-1 & 1  & 1 & 0 & 0\\ 
 1 & 0  & 0 & 0 & 1\\
 0 & -1  & 0 & 1 & 0\\
\end{array} \right]     
$$    

In [ ]:
<table align="center">
    <tr>
        <td align="center">Some other text</td>
        <td align="center">More text</td>
    </tr>
    <tr>
        <td align="center">Some other text 2</td>
        <td align="center">More text 2</td>
    </tr>
</table>

In [1]:
#import matplotlib.pylab as P
import numpy as np

In [2]:
import networkx as nx
import csv

In [3]:
G = nx.MultiDiGraph()

In [4]:
def componentes():
    lEdges = G.edges(keys = True)
    keys=[]
    values = []
    for elem in lEdges:
        l = list(elem)
        u = int(l[0])
        v = int(l[1]) 
        keys.append(l[-1])
        values.append((u, v))
    return dict(zip(keys, values))

def existeComponente(nomeC):
    cc = componentes()
    return cc.has_key(nomeC)


def addComponente(nomeC,tipo, vReal,vImag, nP, nC):
    """
        adiciona um novo componente
        entre dois  vertices
    """  
    #if existeComponente(nomeC):
    #   print ("componente ja definido")
    #   return
    
    G.add_edge(nP, nC, key=nomeC, vReal=vReal, vImag=vImag, tipo=tipo,tensao=0, corrente =0)
    G.add_node(nP, eReal= 0, eImag=0)
    G.add_node(nC, eReal= 0, eImag=0)
    #drawGraph()
    #P.pause(1.5)
    
    
def addComponentes():
    """
    componente eh um ramo do circuito
    nome - tipo - valorReal - valorImag - no partida - no chegada
    addComponente("R1", 'R', 2, 1, 2)
    
    """
    

    with open('circuito1.csv', 'r') as thefile:
        thefile = csv.DictReader(thefile, delimiter=',')
        for row in thefile:
            nComp = row['Nome']
            tComp = row['Tipo']
            vReal = row['vReal']
            vImag = row['vImag']
            nP = row['nP']
            nC = row['nC']
            addComponente(nComp, tComp, float(vReal), float(vImag), int(nP), int(nC))
            #print (nComp, tComp, float(vReal), float(vImag), int(nP), int(nC))
        


In [5]:
addComponentes()

In [6]:
G.edges()

[(0, 2), (1, 2), (1, 3), (1, 3), (2, 0), (2, 1), (2, 3), (3, 0), (3, 1)]

In [7]:
componentes()

{'I1': (3, 1),
 'I2': (2, 1),
 'I3': (0, 2),
 'R1': (1, 3),
 'R2': (1, 3),
 'R3': (2, 3),
 'R4': (2, 0),
 'R5': (1, 2),
 'R6': (3, 0)}

In [8]:
G.nodes()

[0, 1, 2, 3]

In [29]:
def mIncidencia(noRef):
    """
    matriz com total de nos - 1 linhas e r colunas
    """
    Nos = list(set(G.nodes()) - set([noRef]))
    n = len(Nos)
    meusNos = dict(zip(range(1, n+1), Nos))
    ll = componentes()
    m = len(ll)
    mInc = np.zeros((n , m))
    comp = list(ll.values())
    c = list(ll.keys())
    nosV = list(meusNos.values())
    print ('nos = ',nosV)
    print ('comp = ',comp)
    print ('c = ', c)
    for j in range(m):
        vertice = comp[j][0]
        #p = getPolaridade(c[j])
        if (vertice in nosV):
            mInc[nosV.index(vertice)][j] = 1  
        vertice = comp[j][1]
        if (vertice in nosV):
            mInc[nosV.index(vertice)][j] = -1#p
       
            
    
    return np.matrix(mInc)
    
def mFonteTensao():
    """
    matrix com total de r linhas fontes de tensao
    """
    ll = componentes()
    comp = ll.keys()
    m = len(comp)
    Vs = np.zeros((m, 1), dtype=complex)
    for i in range(m): 
        c = comp[i]
        v = getValor(c)
        t = getTipo(c)
        if (t == 'V'):
          Vs[i] = 1.*v
    return np.matrix(Vs)
    
def mFonteCorrente():
    """
    matrix com total r linhas fontes de corrente
    """
    ll = componentes()
    comp = ll.keys()
    m = len(comp)
    Is = np.zeros((m, 1), dtype=complex)
    for i in range(m): 
        c = comp[i]
        v = getValor(c)
        t = getTipo(c)
        #p = getPolaridade(c)
        if (t == 'I'):
          Is[i] = 1.*v
    return np.matrix(Is)
    
def mAdmitancia():
    """
        matriz quadrado r X r com 
        diagonal com admitancias de ramos
    """  
    ll = componentes()
    comp = ll.keys()
    m = len(comp)
    Y = np.zeros((m, m), dtype=complex)
    for i in range(m): 
        c = comp[i]
        v = getValor(c)
        t = getTipo(c)
        if (t == 'V'):
            v = 1e15
        elif (t == 'R'):
            v = 1./v
        elif (t == 'I'):
            v = 0.
        print (' i = %d , Y = %s ' %(i, str(v)))
        Y[i][i] = v
    return np.matrix(Y)


def analise(noRef): 
    A = mIncidencia(noRef)
    Y = mAdmitancia()

    nos = list(set(G.nodes()) - set([noRef]))    
    n = len(nos) 
    
    Is =mFonteCorrente()
    Vs = mFonteTensao()

    print ('\n Nos = ',nos)
    
    ll = componentes()
    comp = ll.keys()
    print ('\n Ramos = ',comp)
    
    print ('\n Incidencia \n ',A)
    print ('\n Is \n ',Is)
    print ('\n Vs \n ',Vs)
    Ybarra = A*Y*A.T
    print ('\n Ybarra  \n',Ybarra)
    Zbarra = Ybarra.I
    print ('\n Zbarra  \n',Zbarra)
    Ibarra = A*(Y*Vs - Is)
    print ('\n Fonte Corrente Resultante  \n',Ibarra)
    
    E = Zbarra*Ibarra
    print ('\n Tensao de barra  \n',E)
    
    Vramo= (A.T)*E
    print ('\n Tensao de Ramo  \n',Vramo)
    Iramo = Y*Vramo
    print ('\n Correntes de Ramo  \n',Iramo)
    # a = float(E[0]) 
    
    for i in range(n): # eReal= 0, eImag=0
        a = float( E[i].real)
        b = float(E[i].imag)
        G.add_node(int(nos[i]), eReal = a,eImag = b )

In [30]:
A = mIncidencia(0)

nos =  [1, 2, 3]
comp =  [(1, 3), (1, 3), (2, 1), (3, 0), (1, 2), (3, 1), (2, 0), (2, 3), (0, 2)]
c =  ['R2', 'R1', 'I2', 'R6', 'R5', 'I1', 'R4', 'R3', 'I3']


In [31]:
A

matrix([[ 1.,  1., -1.,  0.,  1., -1.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  0., -1.,  0.,  1.,  1., -1.],
        [-1., -1.,  0.,  1.,  0.,  1.,  0., -1.,  0.]])

In [ ]:
def setValor(componente, newValor):
    (u,v) = vertices(componente)  
    G.add_edge(u,v,key=componente, valor=newValor)
    
             
  
 
def getComponente(u, v):
    """
        E se houver mais de uma aresta entre dois nos?
    o componente pode ser de v para u
    use um try
    """   
    ll = componentes()
    D = {ll[k]: k for k in ll}
    e = (u, v) 
    if e not in D:
        e = (v, u)
        l = D[e]
        #t = getTipo(l)
        #if (t=='I')or(t=='V'):
        # alterar matriz A
        #chPolaridade(l)
        #p = getPolaridade(l)
        #print '\n Polaridade Trocada', e, ' ' , l, ' -> ' ,p 
        """va = -getValor(l)
        print 30*'-'
        print '\n (%d, %d) = %d ' % (v, u, va) 
        print 30*'-'
        setValor(l, va)"""
    l = D[e]
    
    return l


    
def getDados(componente):
    (u,v) = vertices(componente)
    D = G.get_edge_data(u,v, key=componente)
    return D            
        
def getValor(componente):
    #(u,v) = vertices(componente)
    D = getDados(componente)
    #D = G.get_edge_data(u,v, key=componente)
    z = D['vReal'] + D['vImag']*1.j
    return z

def getTipo(componente):
    (u,v) = vertices(componente)
    D = getDados(componente)
    #D = G.get_edge_data(u,v, key=componente)
    return D['tipo']
    

    
def vertices(nomeEdge):
    d = componentes()
    return d[nomeEdge]

            
def drawGraph():
    edgelist= G.edges(data=True)
    
    P.clf()
    pos = nx.spring_layout(G)
    nx.draw_networkx_nodes(G, pos, node_color = 'r')
    nx.draw_networkx_edges(G,pos, edgelist, edge_color='b', arrows=True)
    nx.draw_networkx_labels(G,pos,font_size=20,font_family='sans-serif')
   
    ll = componentes()
    
    edge_nome= {ll[k]: k for k in ll}
    nx.draw_networkx_edge_labels(G, pos, edge_nome)


# ler componentes de um arquivo
addComponentes()
"""
 digitar o comando 
 
 >>>analise(noRef)
 para ter as tensoes e correntes
     
"""